baseURL = "/"
languageCode = "en-us"
title = "We have moved!"
publishDir = "dist"

[sitemap]
  changefreq = "weekly"

[taxonomies]
  tag = "tags"

[params]
    [params.seo]
    description = "SME DFW Chapter has moved!"
    keywords = ["engineering","manufacturing","sme","smetexaplex","education"]

    [params.social]
    description = "The SME DFW Chapter is now the SME Texaplex Virtual Chapter."
    twitter_handle="@smevirtual"

    [params.external]
    smetexaplex_homepage_url = "https://smetexaplex.com"
