baseURL = "/"
languageCode = "en-us"
title = "We have moved!"
publishDir = "dist"

[sitemap]
  changefreq = "weekly"

[taxonomies]
  tag = "tags"

[params]
    [params.seo]
    description = "SME DFW Chapter has moved!"
    keywords = ["engineering","manufacturing","sme","smevirtual","education"]

    [params.social]
    description = "The SME DFW Chapter has merged with the SME Virtual Network."
    twitter_handle="@smevirtual"

    [params.external]
    smevirtual_homepage_url = "https://smevirtual.com"
