[params]
    [[params.leaders]]
    name = "Adam J. Cook"
    info_url = "https://www.linkedin.com/in/adam-j-cook/"
    title = "Chief Technical Officer"
    company_name = "Alliedstrand"
    company_url = "http://www.alliedstrand.com"
    profile_picture_filename = "adam_cook_profile.png"

    [[params.leaders]]
    name = "Artemio (Art) Palos"
    info_url = "https://www.linkedin.com/in/artemio-palos-2528942b/"
    title = "South West Sales Manager"
    company_name = "Nordson XALOY"
    company_url = "http://www.nordsonpolymerprocessing.com"
    profile_picture_filename = "art_palos_profile.png"

    [[params.leaders]]
    name = "Sunshine Smith"
    info_url = "https://www.linkedin.com/in/sunshine-smith2018/"
    title = "Manufacturing Engineer Sr."
    company_name = "Lockheed Martin Aeronautics"
    company_url = "https://www.lockheedmartin.com"
    profile_picture_filename = "sunshine_smith_profile.png"
